### ISSUE TITLE
previews: webhook to automatically reconcile on github activity

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/devtools#386]
```yaml
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: github-receiver
  namespace: preview
spec:
  type: github
  events:
    - "pull_request"
  secretRef:
    name: preview-webhook-token
  resources:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: immich-github-prs
```

tbd: Create the webhook manually or through TF?
